version: '2'

services:
    maildev:
        container_name: maildev
        image: djfarrelly/maildev:0.13.4
        command:
            - 'bin/maildev'
            - '--smtp'
            - '25'
        ports:
            - '1080:1080'
            - '25:25'
